### ISSUE TITLE
Advertise the participant application form

### ISSUE THREAD

**Issue by BrunoGrandePhD** [hackseq/October_2016#34] opened 2016-06-13 04:14 UTC
I noticed that the Hackseq Twitter account tweeted (now deleted; see screenshot below) the link to the participation form. However, the form isn't even ready yet; it still uses placeholder text for the project titles. I think we're still waiting on having the project descriptions posted in a public repository so the form can link to them. @ttimbers, what's the latest on this?

Going forward, let's ensure proper communication happens prior to these decisions. In this case, we should have confirmed with @santina that the participant form was ready. It sucks to have to delete a tweet that has been retweeted. 

As an aside, Sunday evening might not be the best time to get traction with a tweet. This worked to our advantage this time, because no one submitted an application. 

<img width="651" alt="hackseq_tweet" src="https://cloud.githubusercontent.com/assets/740725/15996744/1c328f9c-30e0-11e6-85d5-fff805f9642c.png">

**Comment by santina** [comment] 2016-06-13 04:44
As soon as the repositories and project descriptions are up, I can update the application form. I also shared it with the Hackseq google account so everyone can edit it. There is also no titles/names for each project, so we'll have to come up with that as well.

**Comment by ttimbers** [comment] 2016-06-13 15:20
Team Leaders projects are now viewable and linkable as Github issues here: https://github.com/hackseq/hackseq_projects_2016/issues

**Comment by ttimbers** [comment] 2016-06-13 15:21
@hackseq/steering_committee Team Leaders projects are now viewable and linkable as Github issues here: https://github.com/hackseq/hackseq_projects_2016/issues

**Comment by Brittdrog** [comment] 2016-06-13 16:05
@ttimbers - Thanks, this is great. I will email the team leaders and let them know that their applications have been successful (with links to the Github issues). I will give them the opportunity to change their titles if they would like (until end of day tomorrow). @santina I will let you know if there are any changes to the titles and then we can open the participant applications on Wednesday if everyone is happy with that.

**Comment by santina** [comment] 2016-06-15 06:31
Thank you for following up on this @ttimbers and @Brittdrog . I have updated the project selection part of the  [application form](https://docs.google.com/forms/d/19rgCe3vTARspXwUWaOWeOSQJ8wKyl0NhpmIEAtPexNg/viewform)  Let me know what you think :)    I simply copied pasted the titles of the issues and used them as the titles of the project.

**Comment by Brittdrog** [comment] 2016-06-15 17:11
Hi @santina. Thanks, this looks great. I received another email from Grace Zheng and have changed her title in Github and the application form. If I receive any more changes, I will update the titles accordingly.

To avoid participants emailing hackseq with questions about time, location, registration etc, I added form notifications and a general info section to the application form. I have set the deadline to 15 July (1 month from now). Let me know if there are any objections to this deadline.

I also changed HackSEQ to hackseq to ensure consistency with the website and twitter account.

If there are no objections, I will send out emails at ~12pm today to the team leaders with links to the participant application forms so that they can start inviting people to join their team.

**Comment by Brittdrog** [comment] 2016-06-15 21:11
Team leaders have been notified about the participant applications. @santina do you think we can start officially advertising the participant applications now (cc @minisciencegirl)?

**Comment by santina** [comment] 2016-06-16 04:33
@Brittdrog Thank you for making those changes !  It's great to have the general information and deadline at the top of the application. The name consistency was a good catch. The form notification is great. I have submitted a test application and did get an email with all the info about hackseq. 

I think it looks good. Maybe someone can offer a second pair of eyes on this and then we can start advertising it.

**Comment by GalenWright** [comment] 2016-06-16 20:40
@santina the form looks great. I made a couple of minor edits (e.g. mentioning that this is an ASHG satellite event and that they have sponsored our travel awards), I hope they help.

**Comment by minisciencegirl** [comment] 2016-06-23 05:04
Hi @santina: Thanks for the great form. Sorry for prematurely tweeting about it. If there's no objection, I can also email this to the UBC departmental email list that I have?

Someone brought up on Twitter about remote participation - what's our stance on this? Or should we let each team leader decide?

**Comment by sjackman** [comment] 2016-06-23 06:07
In person participation is preferred, but I would encourage an eager remote participant to contact the project lead directly.

**Comment by DCGenomics** [comment] 2016-06-23 11:49
As much as I would love to see remote participation work, we've never had
any luck with it (people end up being ~~5% involved).  That said, if
someone could come up with a way to make it work, it would be really
helpful to several coding initiatives.

Based on what we have seen before, it's probably not advisable for folks to
have more than one member of their team remote, and to work on a specific
aim which others are not dependent on.  It is possible that if everyone was
remote, it might work better (e.g. Mozilla sprint), but for some reason,
the mixture doesn't seem to work effectively.  The exceptions to this rule
are people that know in advance that they have to leave a day early, and
other types of work after the Hackathon.

Just my $.02

**Comment by sjackman** [comment] 2016-06-23 16:16
Yes, I agree that the remote participant's duties must be arranged so that nobody else's work depends on them. They could for example handle testing or writing documentation.

**Comment by DCGenomics** [comment] 2016-06-23 16:30
Testing, perhaps for a few teams, might be an excellent role for such a
person!

Perhaps if there is a really qualified person who absolutely can't make it,
they could be assigned to such a role by the organizers.  (I may try this
out in August)

**Comment by minisciencegirl** [comment] 2016-06-23 16:47
Thanks for the input @DCGenomics and @sjackman. I will try to capture this discussion on Twitter (in chunks of 140 characters or less). Do we also want to put a few lines about remote participation on the website?

**Comment by sjackman** [comment] 2016-06-23 18:18
I'm not sure. If it's a common question (more than two people have asked), then yes, otherwise no.

**Comment by minisciencegirl** [comment] 2016-06-23 19:29
Hi I am tweeting out each of the project (and will spread this out over the next few days to generate traffic). I noticed that on our form project 7 and 8 have the same title - but the github repo definitely have 10 different projects: https://docs.google.com/forms/d/19rgCe3vTARspXwUWaOWeOSQJ8wKyl0NhpmIEAtPexNg/viewform

Is this the correct link to use? @santina @ttimbers

**Comment by Brittdrog** [comment] 2016-06-23 19:36
@minisciencegirl I have not heard anything back from Justin Whitehill who proposed Project#3 "Explore high quality RNA-seq data from 2 genotypes of spruce following weevil attack, artificial wounding and untreated controls" so I am not sure if he is still planning on participating. Do you think we should hold off advertising this project until we get confirmation that he will be attending?

**Comment by minisciencegirl** [comment] 2016-06-23 19:47
Sure no problem @Brittdrog. 

I noticed that Melissa has been tweeting out her project, encouraging people to apply to her team/ @hackseq and generating lots of tweets/ discussion. So this could be a good tactic for getting more participants.

**Comment by Brittdrog** [comment] 2016-06-23 19:52
Yeah - I think this is a great idea and I have been encouraging the team leaders to start recruiting/advertising. Tommy Carstensen has also indicated that he already has people interested in his project and that we will not need to worry too much about trying to get participants for his project.

**Comment by adrisua** [comment] 2016-06-23 20:00
@Brittdrog @minisciencegirl I will contact Justin and let you know

**Comment by santina** [comment] 2016-06-23 22:21
Hey @minisciencegirl  I really apologize for the mistake I made in the form, with the duplicate project titles. It was a mistake when I was fixing the form. 

Since then, we had two submissions. I could contact them to see if they would be interested in the project I missed out. Do you think that's appropriate? 

Let me know about project 3.

**Comment by minisciencegirl** [comment] 2016-06-23 22:43
No worries @Santina, it's not a big deal. I just wanted to make sure I didn't tweet the wrong form.

Emailing the two applicants sound reasonable. 

By the way, I am traveling to SF for a conference, so I can't make it to today's meeting. I will keep tweeting each project in the coming week. 

Also let me know if you want me to email the participant application out to VANBUG.

**Comment by adrisua** [comment] 2016-06-26 20:01
@minisciencegirl Thanks for tweeting :) I think sending an email to VANBUG would be fantastic. I contacted some women associations and asked them to cross promote (cmpt-women at SFU, ACM-W, WCT, and of course SCWIST)

**Comment by Brittdrog** [comment] 2016-06-29 01:09
@minisciencegirl - the 9 projects listed on GitHub are all confirmed, so all good to go for tweeting out each of the project. Good idea:-)

**Comment by GalenWright** [comment] 2016-07-06 17:09
The Pharmacogenomics Research Network (PGRN) contacted the gmail account - they are hosting an ASHG satellite symposium (http://www.pgrn.org/ashg-2016.html) from the afternoon of the 17th to the 18th. They offered to share information about hackseq via their twitter account, which they did this morning. I offered to share details  about their event via our twitter too and I will send out a tweet for them today

**Comment by minisciencegirl** [comment] 2016-07-14 22:42
Michelle (undergrad secretary for UBC CS department) sent me the following message:

# 

Hi Amy,

I’ve put the info on our ugrad website but given that it’s summer, the timeline of choosing a project by July 15 is too short.  Is it possible to extend it?

Thanks,
Michele

# 

I know we talked about potentially extending the deadlines for in-town applicants. What's everyone's thoughts on this?

**Comment by ttimbers** [comment] 2016-07-14 22:49
I think we already have lots of participants (what are the current numbers @santina?) so I am not in favour of extending the deadline. But my opinion can certainly be overruled if I am not with the majority...

**Comment by santina** [comment] 2016-07-15 06:34
Hey @ttimbers, we have 62 applicants so far!  Out of that, we have ~8 people applying for a travel award.

@minisciencegirl , I don't see any harm in leaving the application form opened until July 18, since based on an email thread, Shaun won't have time to look at it until then anyway. We won't announce it to everyone, but I'm changing the date the application form.

**Closed as completed** 2016-07-22 00:08 UTC
Labels: task
